version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/app
    networks:
      - shipit
    env_file:
      - .env
    depends_on:
      - pg
    entrypoint: sh -c "npm run start:dev:inspect"

  pg:
    image: 'postgres:16-alpine'
    env_file:
      - .env
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    networks:
      - shipit
    ports:
      - '5432:5432'

networks:
  shipit:
    name: shipit_network
